// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Machine } from "./Machine";

export type UserMachine = { email: string, key: string, machine: Machine, plan: number, presets: string, };
