[package]
name = "renamer-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v7"] }
chrono = "0.4"
ts-rs = "10.1"


[dependencies.mongodb]
version = "3"