name: API Publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_URL }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.REGISTRY_USERNAME}}/renamer-api:latest
          file: api.Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASS: ${{ secrets.SERVER_PASS }}
          DEPOYMENT_PATH: ${{ secrets.API_DEPOYMENT_PATH }}
        run: |
          
          sshpass -p "$PASS" scp -o StrictHostKeyChecking=no docker-compose.yml $USER@$HOST:$DEPOYMENT_PATH
          
          sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            cd $DEPOYMENT_PATH
            docker-compose stop api
            docker-compose rm -f api
            docker-compose pull api
            docker-compose up -d api
          EOF