name: Create Release with Bundles

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

jobs:
  build-darwin:
    name: Build for macOS (Universal)
    runs-on: macos-latest
    defaults:
      run:
        working-directory: tauri-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: './tauri-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build (Darwin Universal)
        run: pnpm tauri build --target universal-apple-darwin

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: |
            tauri-app/src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
            tauri-app/src-tauri/target/universal-apple-darwin/release/bundle/macos/*.tar.gz*

  build-windows:
    name: Build for Windows (x86 and ARM)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: tauri-app
    strategy:
      matrix:
        arch: [ x86_64-pc-windows-msvc, aarch64-pc-windows-msvc ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: rustup target add ${{ matrix.arch }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: './tauri-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build for Windows ${{ matrix.arch }}
        run: pnpm tauri build --target ${{ matrix.arch }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app-${{ matrix.arch }}
          path: |
            tauri-app/src-tauri/target/${{ matrix.arch }}/release/bundle/msi/*.msi*
            tauri-app/src-tauri/target/${{ matrix.arch }}/release/bundle/nsis/*.exe*

  build-linux:
    name: Build for Linux (x86 and ARM)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tauri-app
    strategy:
      matrix:
        arch: [ x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust
        run: rustup update nightly && rustup default nightly

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.arch }}

      # Configuration spécifique pour ARM64
      - name: Setup ARM64 dependencies
        if: matrix.arch == 'aarch64-unknown-linux-gnu'
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev:arm64 \
            libappindicator3-dev:arm64 \
            librsvg2-dev:arm64 \
            pkg-config-aarch64-linux-gnu

      # Configuration spécifique pour x86_64
      - name: Setup x86_64 dependencies
        if: matrix.arch == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: './tauri-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build for Linux ${{ matrix.arch }}
        env:
          PKG_CONFIG_ALLOW_CROSS: ${{ matrix.arch == 'aarch64-unknown-linux-gnu' && '1' || '' }}
        run: |
          if [ "${{ matrix.arch }}" = "aarch64-unknown-linux-gnu" ]; then
            export PKG_CONFIG=aarch64-linux-gnu-pkg-config
          fi
          pnpm tauri build --target ${{ matrix.arch }}

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app-${{ matrix.arch }}
          path: |
            tauri-app/src-tauri/target/${{ matrix.arch }}/release/bundle/appimage/*.AppImage
            tauri-app/src-tauri/target/${{ matrix.arch }}/release/bundle/deb/*.deb
            tauri-app/src-tauri/target/${{ matrix.arch }}/release/bundle/rpm/*.rpm

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ build-darwin, build-windows, build-linux ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}