name: Website Build and Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Build and push
        run: |
          cd renamer-website
          docker build -t ${{ secrets.REGISTRY_URL }}/renamer-website .
          docker push ${{ secrets.REGISTRY_URL }}/renamer-website
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASS: ${{ secrets.SERVER_PASS }}
          DEPOYMENT_PATH: ${{ secrets.API_DEPOYMENT_PATH }}
        run: |
          
          sshpass -p "$PASS" scp -o StrictHostKeyChecking=no docker-compose.yml $USER@$HOST:$DEPOYMENT_PATH
          
          sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            cd $DEPOYMENT_PATH
            docker-compose stop website
            docker-compose rm -f website
            docker-compose pull website
            docker-compose up -d website
          EOF